POST  http://localhost:3003/criar-turma
Content-Type: application/json

{
    "nome": "jemison"
}

###
POST  http://localhost:3003/criar-estudante
Content-Type: application/json

{
    "nome":"Renato Pontes",
    "email":"renato@gmail.com",
    "dataNascimento":"20/09/1990",
    "idTurma":"001"
}


###
POST  http://localhost:3003/criar-docente
Content-Type: application/json

{
    "nome": "Rafael Sander",
    "email": "rafael@gmail.com",
    "dataNascimento": "25/01/1989",
    "idTurma": "001"
}

###
POST  http://localhost:3003/mudar-modulo/:id
Content-Type: application/json

{
    "modulo": 4
}

###
POST  http://localhost:3003/mudar-estudante/:id
Content-Type: application/json

{
    "turma": "002"
}

###
POST  http://localhost:3003/mudar-docente-turma/:id
Content-Type: application/json

{
    "turmaId": "002"
}

###
GET http://localhost:3003/buscar-turmas-ativas


###
GET http://localhost:3003/estudante/:nome

###
GET http://localhost:3003/buscar-docentes

